initialization
initializeDefaults 
	self orientation: self class defaultOrientation;
		labelInterval: self class defaultLabelInterval;
		stepInterval: self class defaultStepInterval;
		min: self class defaultMin;
		max: self class defaultMax;
		legend: self class defaultLegend;
		color: self class defaultColor;
		borderWidth: self class defaultBorderWidth;
		borderColor: self class defaultBorderColor;
		textColor: self class defaultTextColor.