SystemOrganization addCategory: #'StatisticsWorkbench-GUI'!
SystemOrganization addCategory: #'StatisticsWorkbench-Tests'!
SystemOrganization addCategory: #'StatisticsWorkbench-Exceptions'!
SystemOrganization addCategory: #'StatisticsWorkbench-Core'!
SystemOrganization addCategory: #StatisticsWorkbench!
SystemOrganization addCategory: #'StatisticsWorkbench-Examples'!
SystemOrganization addCategory: #'StatisticsWorkbench-Diagrams'!
